#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:/home/latiki/dl/gwt-linux-1.4.61/gwt-user.jar:/home/latiki/dl/gwt-linux-1.4.61/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" edu.harvard.eecs.Latiki;
