#!/bin/sh
APPDIR=`dirname $0`;
java  -cp "$APPDIR/src:$APPDIR/bin:../third_party/gwt/gwt-user.jar:../third_party/gwt/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" -noserver "$@" http://localhost:8111/www/edu.harvard.eecs.Latiki/Latiki.html?repoid=demopaper1 ;
